name: Nodejs CI/CD 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: SonarQube Token
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=node-prom-app
            -Dsonar.organization=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-prom-app:${{ github.sha }} .
       
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-prom-app:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/node-prom-app:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update KubeConfig for EKS
        run: aws eks update-kubeconfig --name nodejs-cluster --region us-east-1

      - name: Test Kubernetes Access
        run: kubectl get nodes
      